workspace.resolver = "3"
workspace.members = [
    "app/alternet",
    "lib/orchestrator",
    "lib/p2p",
    "lib/transport",
]

[workspace.dependencies]
libp2p = { version = "0.56.0", features = [
    "tcp",
    "quic",
    "noise",
    "yamux",
    "mdns",
    "dns",
    "kad",
    "ping",
    "identify",
    "relay",
    "macros",
    "tls",
    "tokio",
    "gossipsub",
    "request-response",
    "dcutr",
] }
tokio = { version = "1.48.0", features = ["full"] }
futures = "0.3.31"
