package.name = "alternet"
package.version = "0.1.0"
package.edition = "2024"
package.publish = false
dependencies.async-trait.version = "*"
dependencies.orchestrator.version = "*"
dependencies.orchestrator.path = "../../lib/orchestrator"
dependencies.tokio.workspace = true
dependencies.p2p.version = "*"
dependencies.p2p.path = "../../lib/p2p"
dependencies.jsonwebtoken.version = "*"
dependencies.jsonwebtoken.features = ["rust_crypto"]
dependencies.redb.version = "*"
dependencies.serde.version = "*"
dependencies.serde.features = ["derive"]
dependencies.anyhow.version = "*"
dependencies.libp2p.workspace = true
dependencies.alternet-transport = { version = "0.1.0", path = "../../lib/transport" }
